version: "3.9"
services:

  mongo:
    image: $IMAGES_MONGO
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ${HOST_PATHS_PROJECT_DATA_PATH}/mongo:/data/db

  postgis:
    image: $IMAGES_POSTGIS
    container_name: postgis
    restart: unless-stopped
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ${HOST_PATHS_PROJECT_DATA_PATH}/postgis/data:/var/lib/postgresql/data
    deploy:
      resources:
        # limits or reservations ?
        reservations:
          memory: 8G

  rabbitmq:
    image: $IMAGES_RABBITMQ
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  bioformat:
    image: $IMAGES_BIOFORMAT
    container_name: bioformat
    restart: unless-stopped
    ports:
      - "4321:4321"
    volumes:
      - ${HOST_PATHS_PROJECT_DATA_PATH}/images:$CONTAINER_PATHS_IMAGES
  
  pims-cache:
    image: $IMAGES_PIMS_CACHE
    container_name: pims-cache
    restart: unless-stopped
    ports:
      - 6379:6379


  web_ui:
    build:
      context: $HOST_PATHS_WEB_UI_SRC
      dockerfile: docker/Dockerfile
      target: dev-server
      args:
        SCRIPTS_REPO_TAG: latest
    ports:
      - "$WEB_UI_PORT:$WEB_UI_PORT"
    working_dir: "/app"
    container_name: web_ui
    restart: unless-stopped
    volumes:
      - $HOST_PATHS_WEB_UI_SRC:/app
      - /etc/localtime:/etc/localtime

  nginx:
    image: $IMAGES_NGINX
    container_name: nginx
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - web_ui
    ports:
      - 80:80
    volumes:
      - ${HOST_PATHS_PROJECT_DATA_PATH}/upload:$CONTAINER_PATHS_UPLOADED
  
  # to map nginx ip with urls to host's /etc/hosts
  etc_hosts_rewriter:
    image: alpine:latest
    entrypoint: ["/bin/sh", "/cm_configs/rewrite.sh"]
    depends_on:
      - nginx
    volumes:
      - /etc:/local_etc/