services:
  web_ui:
    image: web-ui:dev-latest
    build:
      context: ./repos/Cytomine-web-ui/
      dockerfile: ./docker/Dockerfile
      target: dev-server
      args:
        SCRIPTS_REPO_TAG: latest
    working_dir: "/app"
    restart: unless-stopped
    env_file: ./envs/web_ui.env
    volumes:
      - ./repos/Cytomine-web-ui:/app
    environment:
      PORT: ${DEV_UI_PORT:-80}
      NODE_ENV: development
