stages:
  - lint
  - test

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: always
    - when: never

lint-javascript:
  stage: lint
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:${NODE_VERSION}
  before_script:
    - npm ci
  script:
    - npm run lint

lint-dockerfile:
  stage: lint
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/hadolint/hadolint:${HADOLINT_VERSION}
  script:
    - hadolint docker/Dockerfile
  rules:
    - changes:
        - docker/Dockerfile

unit-test:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:${NODE_VERSION}
  before_script:
    - npm ci
  script:
    - npm run test
  artifacts:
    when: always
    paths:
      - coverage/
      - reports/
